# Generated by Django 3.2.9 on 2021-11-29 23:11

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='first name')),
                ('last_name', models.CharField(max_length=200, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='email')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='phone number')),
                ('gender', models.CharField(choices=[('1', 'Female'), ('2', 'Male'), ('3', 'Other'), ('4', 'Prefer to not say')], max_length=15, verbose_name='genders')),
                ('number', models.PositiveIntegerField(verbose_name='number')),
                ('image', models.ImageField(default='students/avatar.png', upload_to='students/%Y/%m/%d/', verbose_name='image')),
            ],
        ),
    ]
