# Generated by Django 3.2.9 on 2021-12-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211207_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='number'),
        ),
    ]
