# Generated by Django 3.2.9 on 2021-12-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_students_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(default='students/avatar.png', upload_to='students/%Y/%m/%d/', verbose_name='image'),
        ),
    ]
